### PR TITLE
Fix exit code.

### LINKED ISSUE #31: Exit code (v0.4.0)
Shouldn't the script generate error when some unused variable is found ?

Spec :
Using Npm version

Expected behavior (0.3.3):

v0.4.0 behavior:

### PR DESCRIPTION
**Pull request by XhmikosR**
Fixes #31

### CODE REVIEW

File: cli.js [hunk 1]
```diff
@@ -52,6 +52,8 @@ function main(args) {
     }
 
     spinner.stop();
+
+    process.exit(unusedList.length);
```
Comment (Johann-S) [inline cli.js]: Shouldn't we follow some rules about command lines exit codes? For example: https://www.tldp.org/LDP/abs/html/exitcodes.html

Comment (XhmikosR) [reply cli.js]: Well, it depends. If no error occurs, we exit with `0`. Then instead of `1` we just exit with `>=1`.

Either way works for me, but this solution has the advantage you can tell the number of unused variables by the exit code.

Comment (Johann-S) [reply cli.js]: I would prefer to display clearly the number of unused variables instead of an error code which shows that, but your call here
